[api_credentials]
api_key = "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"
bard_session = "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"
phind_cf_clearance = "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"
